[api_credentials]
api_key = "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"
bard_session = "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"
phind_cf_clearance = "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"
